server:
  error:
    whitelabel:
      enabled: false
  port: 8080

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
  graphql:
    graphiql:
      enabled: true
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: public
    show-sql: true
  thymeleaf:
    cache: false